appVersion: "0.5"
description: A Helm chart to install virtual kubelet inside a Kubernetes cluster.
icon: https://avatars2.githubusercontent.com/u/34250142
maintainers:
- email: junjiez@microsoft.com
  name: Robbie Zhang
name: virtual-kubelet
sources:
- https://github.com/virtual-kubelet/virtual-kubelet
version: 0.5.0
