apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: osba-cosmos-mongodb-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: osba-cosmos-mongodb-demo
    spec:
      containers:
      - name: osba-cosmos-mongodb-demo
        image: vlakstest1b359.azurecr.io/hello-osba:v1
        imagePullPolicy: Always        
        ports:
        - containerPort: 80
        env:
        - name: MONGO_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              key: connectionString
              name: mdbsesecret
      imagePullSecrets:
        - name: taskapiacrsecret               