apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
 name: demo-aad1
spec:
 type: 0
 ResourceID: /subscriptions/0d4f44f5-e032-49de-ba6c-86dcf4201a31/resourcegroups/MC_ais-istio2-rg_taskapi-istio2_eastus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/demo-aad1
 ClientID: 148a9252-21cb-4fbb-8c43-afd14e73560c
