apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostname-file
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hostname-file  
  template:
    metadata:
      labels:
        app: hostname-file
        version: v1
    spec:
      volumes:
      - name: azurefilepv
        persistentVolumeClaim:
          claimName: aksclassazurefilepvc
      containers:
      - image: rstarmer/hostname:v1
        imagePullPolicy: Always
        name: hostname
        volumeMounts:
          - mountPath: "/www"
            name: azurefilepv
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hostname-file
  name: hostname-file
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
  selector:
    app: hostname-file
