kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: backend-policy
  namespace: mysqlhelm   
spec:
  podSelector:
    matchLabels:
      app: mysql-1601210421
      release: mysql-1601210421
  ingress:
  - from:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          run: ubuntu
