apiVersion: v1
kind: ServiceAccount
metadata:
  name: foo-sa
  namespace: rbac-apiserver
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  namespace: rbac-apiserver
  name: foo-cr
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services", "endpoints", "pods", "secrets"]
  verbs: ["get", "watch", "list"]
---
# The role binding to combine the secret-access service account and role
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: access-rb
subjects:
- kind: ServiceAccount
  name: foo-sa
  namespace: rbac-apiserver  
roleRef:
  kind: ClusterRole
  name: foo-cr
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: curl-custom-sa
  namespace: rbac-apiserver  
spec:
  serviceAccountName: foo-sa
  containers:
  - name: main
    image: tutum/curl
    command: ["sleep", "9999999"]
  - name: ambassador
    image: luksa/kubectl-proxy:1.6.2
