kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cloud-storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: cloud-storage

