apiVersion: v1
kind: Pod
metadata:
  name: pod-example
  labels:
    app: kuard
    environment: prod

spec:
  containers:
  - name: kuard
    image: gcr.io/kuar-demo/kuard-amd64:1
    ports:
    - containerPort: 80