apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
 name: demo-aad1
spec:
 type: 0
 ResourceID: /subscriptions/0d4f44f5-e032-49de-ba6c-86dcf4201a31/resourcegroups/MC_vlakstest4_RG_vlakstest4cluster_eastus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/demo-aad1
 ClientID: 1c79d0f2-3383-408f-a3ee-75e1701b6fc0
