apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ds-example
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        env: rev2
    spec:
      nodeSelector:
        nodeType: Edge
      containers:
      - name: nginx
        image: nginx:stable-alpine
        ports:
        - containerPort: 80